name: bank_sha
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
